### ISSUE TITLE
Discussion: Clickable image - Like Buttons / Pagination Buttons

### ISSUE THREAD

**Issue by Suit-GitHub** [sumac-theme/SUMACTumblrTheme#10]
When you click on an image, it gives you the option to like and re-blog, which is awesome, but then the pagination buttons go away. Not sure how you would fix this.

**Comment by sumac-theme** [comment]
Like and reblog should be available options without clicking.

To remove clickthrough, you can disable the "Click Photo opens Permalink" theme variable. Let me know if this is what you're looking for.

**Comment by Suit-GitHub** [comment]
Is the like button available/ suppose to be showing? I did not see it on the comments section. I did see re-blog though 

Link to image ref: https://imgur.com/a/0JTg3Kk

**Comment by sumac-theme** [comment]
> Is the like button available/ suppose to be showing? I did not see it on the comments section. I did see re-blog though
> 
> Link to image ref: https://imgur.com/a/0JTg3Kk

Maybe Tumblr blocks the like button on your own posts. Do you see the like button in incognito? They're there for me.

**Comment by Suit-GitHub** [comment]
> Maybe Tumblr blocks the like button on your own posts. Do you see the like button in incognito? They're there for me.

Yea, I'm using a completely different account. Running Firefox Version 78.0.2 (64-bit)
Just checked on Chrome, and you are correct. It is there on Chrome. Which is a step up from the old theme which did not work on chrome. 

Upon further debugging, it seems that U-Block is preventing the like button to appear. It seems that the "cosmetic filter" is the cause. 

Image for Ref: https://imgur.com/a/xele7BT

Not 100% sure why it only kills the like button out of everything else, and again, not sure how that would be resolved.

Edit: Upon even further review, the like button is there for the old theme when UBlock is disabled. Which is strange, I could have sworn it was never working for me before. So unless you know how to bypass UBlock, the "Like Button" 'bug' is resolved.

**Comment by sumac-theme** [comment]
> Edit: Upon even further review, the like button is there for the old theme when UBlock is disabled. Which is strange, I could have sworn it was never working for me before. So unless you know how to bypass UBlock, the "Like Button" 'bug' is resolved.

I'm using Tumblr's `{LikeButton color="white"}` variable, so I don't think I could come up with a way to resolve this. It injects a *really* complicated `iframe` into the theme which UBlock must think is an advertisement.

Closing issue. Don't think I could implement my own custom like button with my limited Tumblr knowledge (assuming that's even possible).
